openapi: 3.0.3
info:
  description: 'Spec for the IoTAgent-Turtle agent'
  version: 0.0.1
  title: IoTAgentTurtle
  contact:
    email: fernando.lopez@fiware.org
externalDocs:
  description: Implementation on github.
  url: 'https://github.com/flopezag/IoTAgent-Turtle'
tags:
  - name: Ops
    description: Method to provide health info about the service information
  - name: Parse
    description: Perform the parse operation.
paths:
  '/version':
    get:
      tags:
        - Ops
      description: Provide the current health status and information vertsion of IoTAgent-Turtle.
      operationId: getversion
      responses:
        '200':
          description: Service is up and running and provide description information about the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'

  '/parse':
    post:
      tags:
        - Parse
      description: Parse a SDMX Turtle file into a NGSI-LD (JSON-LD) format.
      operationId: parse
      requestBody:
        required: true
        content:
          form-data:
            schema:
              $ref: '#/components/schemas/TurtleFile'
      responses:
        '201':
          description: File succesfully read, parsed, and forwarded to the FIWARE Context Broker.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
        '500':
          description: Did not receive a valid NGSI-LD Entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
        '400':
          description: Did not receive a valid NGSI-LD Entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
        '408':
          description: Did not receive a valid NGSI-LD Entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
        '503':
          description: Did not receive a valid NGSI-LD Entity.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
components:
  schemas:
    VersionInfo:
      type: object
      description: Status of the running service
      properties:
        doc:
          type: string
          description: Link to the documentation of the component.
          example: "UP"
        git_hash:
          type: string
          description: Git hash of the current executed version.
          example: "UP"
        version:
          type: string
          description: Current version of the IoTAgent-Turtle server.
          example: "UP"
        release_date:
          type: string
          description: Release date of the executed IoTAgent-Turtle server.
          example: "UP"
        uptime:
          type: string
          description: Time that the IoTAgent-Turtle server is up and running.
          example: "UP"
      required:
        - doc
        - git_hash
        - version
        - release_date
        - uptime

    TurtleFile:
      type: string
      format: binary
      description: |
        This is a string
        in multiple lines.

        And an extra one.
